meta_product_name: "Le Wallet"
meta_title: "Le Wallet - Tus finanzas simplificadas"
meta_description: "La unica app que consolida tus cuentas bancarias en una sola plataforma"
meta_image: "logo.png" # should exist in `app/assets/images/`
